version: '3'

services:
  cms:
    image: cms
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cms
    ports:
      - '5432:5432'
    networks:
      - default

volumes:
  postgres:
  node_modules:
