/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    forms: Form;
  };
  globals: {};
}
export interface User {
  id: string;
  firstName?: string;
  lastName?: string;
  roles?: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Form {
  id: string;
  title: string;
  description?: string;
  type?: string;
  fields?: (
    | {
        key: string;
        title?: string;
        description?: string;
        default?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'string-type';
      }
    | {
        key: string;
        title?: string;
        description?: string;
        default?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'number-type';
      }
    | {
        key: string;
        title?: string;
        description?: string;
        default?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'integer-type';
      }
    | {
        key: string;
        title?: string;
        description?: string;
        default?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'boolean-type';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
